#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

OLD_APP_NAME="$1"
NEW_APP_NAME="$2"
for SERVICE in $(fn-services-list false); do
  in_links_file "$SERVICE" "$OLD_APP_NAME" || continue
  remove_from_links_file "$SERVICE" "$OLD_APP_NAME"
  add_to_links_file "$SERVICE" "$NEW_APP_NAME"
  mv "$PLUGIN_DATA_ROOT/$SERVICE/links/$OLD_APP_NAME" "$PLUGIN_DATA_ROOT/$SERVICE/links/$NEW_APP_NAME"
done
