#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

APP="$1"
for SERVICE in $(fn-services-list false); do
  in_links_file "$SERVICE" "$APP" || continue
  STATUS="$(service_status "$SERVICE")"
  if [[ "$STATUS" != running && "$STATUS" != restarting ]]; then
    dokku_log_warn "$PLUGIN_SERVICE service $SERVICE is not running; starting it"
    service_start "$SERVICE"
  fi
done
