#!/usr/bin/env bash

source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

[[ "$1" == "$PLUGIN_COMMAND_PREFIX:app-links" ]] && shift
declare APP="${1:-$DOKKU_APP_NAME}"
[[ -n "$APP" ]] || dokku_log_fail "Please specify an app"
verify_app_name "$APP"
service_app_links "$APP"
