#!/usr/bin/env bash

source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

[[ "$1" == "$PLUGIN_COMMAND_PREFIX:enter" ]] && shift
declare SERVICE="${1:-}"
verify_service_name "$SERVICE"
shift
service_enter "$SERVICE" "$@"
